[package]
name = "torch_yolo_expr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.8.0"
opencv = "0.77.0"
onnxruntime = "0.0.13"